config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', edit: 'profile' },
                     controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  get 'pages/about'
  get '/myprojects' => 'project#list'

  post '/free' => 'charges#free'
  post '/create' => 'charges#create'

  get 'static_pages/privacy'
  get 'static_pages/term'

  root 'pages#about'

  resources :project do
    resources :task, only: [:show]
  end

  resources :project do
    resources :reviews, only: [:create, :destroy]
  end

  resources :blogs

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
	<% resource.errors.full_messages.each do |msg| %>
		toastr.error('<%= msg %>')
	<% end %>
	</script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer grey darken-3">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">C4S-JP</h5>
        <p class="grey-text text-lighten-4">C4S-JPは、Code4Startup.comと提携した日本のサイトです。実在する素晴らしいＷＥＢサイトを参考に、サイトの作り方（プログラミング方法）を動画で学ぶことができます。C4S-JPは、
日本独自コンテンも追加して行く予定です。  </p>
      </div>
      
      <div class="col l3 s12">
        <h5 class="white-text">Navigate</h5>
        <ul>
          <li><%= link_to "プライバシーポリシー", static_pages_privacy_path, class: "white-text" %></li>
          <li><%= link_to "利用規約", static_pages_term_path, class: "white-text" %></li>
        </ul>
      </div>
      
      <div class="col l3 s12">
        <h5 class="white-text">Social</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Twitter(準備中)</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Facebook(準備中)</a></li>
        </ul>
      </div>
      
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2016 Copyright Code4Startup-JP
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav>
    <div class="container">
      <div class="nav-wrapper">

        <%= link_to root_path, class: 'navbar-brand' do %>
				  <div class="logo">
						<%= image_tag('hdrLogo.png', alt: 'logo') %>
					</div>
				<% end %>

        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%= link_to "コース一覧", project_index_path %></li>
          <% if(!user_signed_in?) %>
            <li><%= link_to "会員登録(無料)", new_user_registration_path %></li>
            <li><%= link_to "ログイン", new_user_session_path %></li>
          <% else %>
            <li><%= link_to "アカウント情報", edit_user_registration_path %></li>
            <li><%= link_to "受講中のコース", myprojects_path %></li>
            <li class="divider"></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
	<% flash.each do |f| %>
	<% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
		toastr['<%= type %>']('<%= f[1] %>')
	<% end %>
	</script>
<% end %>