config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', edit: 'profile' },
                     controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  get 'pages/about'
  get '/myprojects' => 'project#list'

  post '/free' => 'charges#free'
  post '/create' => 'charges#create'

  get 'static_pages/privacy'
  get 'static_pages/term'

  root 'pages#about'

  resources :project do
    resources :task, only: [:show]
  end

  resources :project do
    resources :reviews, only: [:create, :destroy]
  end

  resources :blogs

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  has_many :tasks

  has_many :subscriptions
  has_many :users, through: :subscriptions

  has_many :reviews

  validates :name, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 1000 }
  validates :price, presence: true, numericality: { only_integer: true }

  has_attached_file :image, styles: { medium: '680x300>', thumb: '170x75>' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  do_not_validate_attachment_file_type :image

  def shortname
    name.length > 25 ? name[0..25] + '...' : name
  end

  def average_rating
    reviews.blank? ? 0 : reviews.average(:star).round(2)
  end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  before_action :authenticate_user!, only: [:list]

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    session[:project_id] = @project.id
    @tasks = @project.tasks.order(:tag)

    @joined = false

    if !current_user.nil? && !current_user.projects.nil?
      @joined = current_user.projects.include?(@project)
    end

    @users = @project.users.order('created_at desc').first(10)

    @review = Review.new
    @reviews = @project.reviews

    @hasReview = @reviews.find_by(user_id: current_user.id) if current_user
  end

  def list
    @projects = current_user.projects unless current_user.nil?
  end
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/project/index.html.erb
<section class="sub-banner sub-banner-course">
  <div class="awe-static bg-sub-banner-course"></div>
  <div class="container">
  <div class="sub-banner-content">
    <h2 class="text-center">コース一覧</h2>
  </div>
  </div>
</section>


<section id="categories-content" class="categories-content">
        <div class="container">

<div class="row" data-no-turbolink>
    <!-- CATEGORIES CONTENT -->
	<% @projects.each do |project| %>
		<%= link_to project do %>
			<div class="col s12 m6 l3">
				<div class="card small mc-item">
					
					<div class="card-image">
						<%= image_tag project.image.url %>
					</div>
					
					<div class="card-content" style="height: 6em">
						<span class="card-title grey-text text-darken-1">
						<h4><%= project.shortname %></h4>

							 <div class="name-author text-bottom">
                                     <a>By BProCoder</a>
                            </div>
						</span>
						<span class="card-action grey-text text-darken-1 text-right">
						<i class="small material-icons">shopping_cart</i>
						<%= project.price == 0? "Free" : "￥#{project.price}" %>
						</span>
					</div>

				</div>
			</div>
		<% end %>
	<% end %>
</div>



</div>
</section>

app/views/project/list.html.erb
<section class="sub-banner sub-banner-course">
  <div class="awe-static bg-sub-banner-course"></div>
  <div class="container">
    <div class="sub-banner-content">
      <h2 class="text-center">受講しているコース一覧</h2>
    </div>
  </div>
</section>

<section id="categories-content" class="categories-content">
  <div class="container">
    <div class="row" data-no-turbolink><br/>

      <% if @projects.count > 0 %>
        <% @projects.each do |project| %>
          <%= link_to project do %>
	      	  <div class="col s12 m6 l3">
      				<div class="card small mc-item">
	      				<div class="card-image">
		      				<%= image_tag project.image.url %>
		      			</div>

		      			<div class="card-content" style="height: 6em">
			      			<span class="card-title grey-text text-darken-1">
		      				  <h4><%= project.shortname %></h4>
                    <div class="name-author text-bottom">
                      <a>By BProCoder</a>
                    </div>
	      					</span>
		      				<span class="card-action grey-text text-darken-1 text-right">
		      				  <i class="small material-icons">shopping_cart</i>
			      			  <%= project.price == 0? "Free" : "￥#{project.price}" %>
			      			</span>
		      			</div>
		      		</div>
	      		</div>
	        <% end %>
	      <% end %>
      <% else %>
	      <div class="center">
		      <h5>Currently you're not in any projects!</h5>
	      	<%= link_to "Show me all Projects", root_path, class: "btn btn-primary" %>
      	</div>
      <% end %>

    </div>
  </div>
</section>

app/views/project/show.html.erb
<% content_for :head do %>
	<title><%= @project.name %> | BProCoder</title>
	
	<!-- Twitter Card data -->
	<meta name="twitter:card" content="summary_large_image">
	<meta name="twitter:site" content="@BProCoder">
	<meta name="twitter:creator" content="@BProCoder">
	<meta name="twitter:title" content="<%= @project.name %>">
	<meta name="twitter:description" content="<%= @project.content %>">
	<meta name="twitter:image:src" content="<%= image_url @project.image %>">

	<!-- Open Graph data -->
	<meta property="og:site_name" content="BProCoder">
	<meta property="og:type" content="website">
	<meta property="og:title" content="<%= @project.name %>">
	<meta property="og:description" content="<%= @project.content %>">
	<meta property="og:image" content="<%= @project.image %>">
<% end %>


<section class="sub-banner sub-banner-course">
  <div class="awe-static bg-sub-banner-course"></div>
  <div class="container">
    <div class="sub-banner-content">
      <h2 class="text-center">コース：<%= @project.shortname %></h2>
    </div>
  </div>
</section>

<div class="course-top row">
	<div class="container">
  <div class="col m4">
    <div class="card video-course-intro z-depth-2">
    	<div class="card-image">
				<%= image_tag @project.image.url %>
			</div>

<% if !@joined %>
  <!-- 受講していない生徒用 -->

	<div class="card-action center">
	  <% if user_signed_in? %>
    <!-- 受講していない＋ログイン済み -->
		  <% if @project.price == 0 %>
      <!-- 無料コース　～　受講していない＋ログイン済み -->
		    <%= form_tag free_path do %>
			    <%= hidden_field_tag 'project_id', @project.id %>
			    <h3 class="price">Free</h3>
			    <button type="submit" class="btn light-blue">受講する</button>
			  <% end %>
      <!-- 無料コース　～　受講していない＋ログイン済み ここまで -->
			<% else %>
      <!-- 有料コース　～　受講していない＋ログイン済み -->
        <%= form_tag create_path, id:'chargeForm' do %>
		      <%= hidden_field_tag 'stripeToken' %>
			    <%= hidden_field_tag 'stripeEmail' %>
			    <%= hidden_field_tag 'project_id', @project.id %>
			    <h3 class="price">￥<%= @project.price %></h3>
          <button id="customButton" class="btn light-blue">決済ページへ</button><br/>

          <script>
            var handler = StripeCheckout.configure({
              key: '<%= Rails.configuration.stripe[:publishable_key] %>',
              token: function(token, arg) {
                $('#stripeToken').val(token.id);
                $('#stripeEmail').val(token.email);
                $('#chargeForm').submit();
              }
            });
            document.getElementById('customButton').addEventListener('click', function(e) {
              handler.open({
                name: 'LibreCoding',
                description: '<%= @project.name %>',
                currency: 'jpy',
                amount: '<%= @project.price %>',
                email: '<%= current_user.email %>'
              });
              e.preventDefault();
            });
          </script>

			  <% end %>
			<% end %>
      <!-- 有料コース　～　受講していない＋ログイン済み 　ここまで -->
		<% else %>
    <!-- ログインしていない -->

    <h3 class="price"><%= @project.price == 0? "Free" : "￥#{@project.price}" %></h3>
			<%= link_to new_user_session_path do %>
				<button type="submit" class="btn light-blue">ログインページへ</button>
			<% end %>
		<% end %>
	</div>

<!-- 受講している生徒用 -->
<% else %>
	<div class="card-action center">
    <a href="#videos" class="btn light-blue">カリキュラムを見る</a><br/>
	</div>
<% end %>
		</div>
	</div>
<!-- 左サイドバー　ここまで -->

	<div class="col m8">
		<div class="card2">


			<div class="row">
		    <div class="col s12">
		      <ul class="tabs">
		        <li class="tab col s6"><a class="active" href="#about">コース概要</a></li>
		        <li class="tab col s6"><a href="#videos">カリキュラム一覧</a></li>
		      </ul>
		    </div>
		    <div id="about" class="col s12">
		    	<div class="card-content grey-text text-darken-4">
		    		<div><%= markdown(@project.content) %></div>
		    		<br>
						<span id="average_rating"></span>
						<p> <%= @reviews.count %> <%= @reviews.count > 1? "Reviews" : "件の評価" %></p>
						<hr>
						

						<div><%= render 'reviews/form' if @joined && !@hasReview %></div>
						<div><%= render 'reviews/index' %></div>

					</div>
		    </div>

		    <div id="videos" class="col s10 offset-s1">
		    	<div class="collection section-outline" data-no-turbolink>
						<% @tasks.each do |task| %>
							<% if task.header %>
								<div class="tit-section xsm">
									<i class="mdi-social-school"> <%= task.title %></i>
								</div>
							<% else %>
								<%= link_to [task.project, task], class: "collection-item" do %>
									<%= task.title %>
								<% end %>
							<% end %>
						<% end %>
					</div>
		    </div>
		  </div>

		</div>
	</div>
</div>
</div>


<script>
	$('#average_rating').raty({
		path: '/images',
		readOnly: true,
		score: <%= @project.average_rating %>
	});
</script>